name = "render-keep-alive"
main = "src/index.js"
compatibility_date = "2025-07-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "STATUS_KV"
id = "c8694117e38a4bc8b4600a37023f9eba"

[triggers]
crons = ["*/5 * * * *"]
